#!/usr/bin/env bash
set -uo pipefail
#
# BuildBud Project Genesis — host infrastructure scanner.
#
# READ-ONLY: inspects the host (OS, resources, users, ports, services, docker,
# databases, domains, firewall, CI, existing BuildBud) and writes a markdown
# report. Runs no mutations — every probe is a read (GET/inspect/status). Safe
# to run on any box, with or without sudo (some probes degrade gracefully
# without it). This is step 2 of genesis ("inspect reality") — its output seeds
# the blueprint's Infrastructure section.
#
# Usage:
#   ./inspect.sh                     # scan localhost -> ./INFRASTRUCTURE_SCAN.md
#   ./inspect.sh --out /path/scan.md # custom output path
#   ./inspect.sh --stdout            # print to stdout instead of a file
#
BLU='\033[0;34m'; GRN='\033[0;32m'; YLW='\033[1;33m'; NC='\033[0m'
info(){ echo -e "${BLU}[inspect]${NC} $*" >&2; }
ok(){ echo -e "${GRN}[inspect]${NC} $*" >&2; }

OUT="./INFRASTRUCTURE_SCAN.md"
TO_STDOUT=false
while [[ $# -gt 0 ]]; do case $1 in
  --out) OUT="$2"; shift 2;;
  --stdout) TO_STDOUT=true; shift;;
  *) echo "unknown option: $1" >&2; exit 1;; esac; done

have(){ command -v "$1" >/dev/null 2>&1; }
# Best-effort probe: run $* , echo output, never fail the script.
probe(){ "$@" 2>/dev/null || true; }
# sudo -n only if available and passwordless; else run bare (may return less).
maybe_sudo(){ if have sudo && sudo -n true 2>/dev/null; then sudo -n "$@" 2>/dev/null; else "$@" 2>/dev/null; fi; }

info "Scanning host (read-only)..."
TS="$(probe date -u +%Y-%m-%dT%H:%M:%SZ)"
HOST="$(probe hostname)"

emit(){ cat <<REPORT
# Infrastructure Scan — ${HOST:-unknown}

> Generated by BuildBud Project Genesis \`inspect.sh\` at ${TS}. Read-only host
> discovery. Seeds the project blueprint's Infrastructure section. Re-run any
> time; nothing here is mutated on the host.

## Host
- **Hostname:** ${HOST:-?}
- **OS:** $(probe bash -c '. /etc/os-release 2>/dev/null && echo "$PRETTY_NAME"' || echo '?')
- **Kernel:** $(probe uname -r) ($(probe uname -m))
- **Uptime:** $(probe uptime -p)

## Resources
- **CPU:** $(probe nproc) cores — $(probe bash -c "grep -m1 'model name' /proc/cpuinfo | cut -d: -f2 | sed 's/^ //'")
- **Memory:** $(probe bash -c "free -h | awk '/^Mem:/{print \$2\" total, \"\$7\" available\"}'")
- **Disk (/):** $(probe bash -c "df -h / | awk 'NR==2{print \$2\" total, \"\$4\" free (\"\$5\" used)\"}'")

## Network
- **Public IP:** $(probe bash -c "curl -s --max-time 4 ifconfig.me || echo 'n/a (no egress or curl)'")
- **Tailscale:** $(if have tailscale; then probe bash -c "tailscale ip -4 2>/dev/null | head -1 | sed 's/^/present, IP /' || echo 'installed, not up'"; else echo 'not installed'; fi)
- **Listening ports (TCP):**
\`\`\`
$(maybe_sudo ss -tlnp 2>/dev/null | awk 'NR==1||/LISTEN/{print}' | head -40 || probe ss -tln | head -40)
\`\`\`

## Services (systemd, running)
\`\`\`
$(probe systemctl list-units --type=service --state=running --no-legend --no-pager | awk '{print $1}' | head -40)
\`\`\`

## Docker
- **Installed:** $(if have docker; then probe docker --version; else echo 'no'; fi)
- **Compose:** $(if have docker && docker compose version >/dev/null 2>&1; then probe docker compose version | head -1; else echo 'no'; fi)
- **Running containers:**
\`\`\`
$(if have docker; then maybe_sudo docker ps --format 'table {{.Names}}\t{{.Image}}\t{{.Ports}}' 2>/dev/null | head -30 || echo 'docker present, cannot list (perms?)'; else echo 'docker not installed'; fi)
\`\`\`

## Databases (detected by port/process/container)
$(
  found=""
  for db in "postgres:5432" "mysql:3306" "mariadb:3306" "redis:6379" "mongodb:27017"; do
    n="${db%%:*}"; p="${db##*:}"
    if pgrep -x "$n" >/dev/null 2>&1 || ss -tln 2>/dev/null | grep -q ":${p} "; then
      echo "- **${n}** — likely present (process or port ${p})"; found=1
    fi
  done
  # falkordb shares redis's port 6379 — detect by process or container image instead
  if pgrep -f falkordb >/dev/null 2>&1 || { have docker && maybe_sudo docker ps --format '{{.Image}}' 2>/dev/null | grep -qi falkordb; }; then
    echo "- **falkordb** — likely present (process or container)"; found=1
  fi
  [[ -z "$found" ]] && echo "- none detected"
)

## Domains / reverse proxy
- **Caddy:** $(if have caddy || probe pgrep -x caddy >/dev/null; then echo 'present'; else echo 'no'; fi)
- **Nginx:** $(if have nginx || probe pgrep -x nginx >/dev/null; then echo 'present'; else echo 'no'; fi)
- **Configured domains (best-effort):**
\`\`\`
$( d=$(maybe_sudo grep -rhoE '([a-z0-9-]+\.)+[a-z]{2,}' /etc/caddy /etc/nginx 2>/dev/null | grep -vE '\.(crt|key|pem|conf|log|json|ya?ml|txt|sock)$' | grep -vE '^(schema|www|example|localhost)\.' | sort -u | head -15); [[ -n "$d" ]] && echo "$d" || echo 'none found' )
\`\`\`

## Firewall / intrusion
- **UFW:** $(if have ufw; then maybe_sudo ufw status 2>/dev/null | head -1 || echo 'installed'; else echo 'not installed'; fi)
- **fail2ban:** $(if have fail2ban-client || probe pgrep -x fail2ban-server >/dev/null; then echo 'present'; else echo 'not installed'; fi)
- **SSH root login:** $(maybe_sudo sshd -T 2>/dev/null | awk '/^permitrootlogin/{print $2}' | head -1 || probe grep -iE '^PermitRootLogin' /etc/ssh/sshd_config | awk '{print $2}' | head -1 || echo '?')
- **SSH password auth:** $(maybe_sudo sshd -T 2>/dev/null | awk '/^passwordauthentication/{print $2}' | head -1 || echo '?')

## CI / dev infra on this host
- **Gitea:** $(if probe ss -tln | grep -q ':3002 ' || probe pgrep -f gitea >/dev/null; then echo 'likely (port 3002 / process)'; else echo 'no'; fi)
- **Woodpecker:** $(if probe pgrep -f woodpecker >/dev/null; then echo 'likely'; else echo 'no'; fi)
- **GitHub runner:** $(if probe pgrep -f 'actions.runner|Runner.Listener' >/dev/null; then echo 'likely'; else echo 'no'; fi)

## Existing BuildBud on this host
- **BuildBud container:** $(if have docker && maybe_sudo docker ps --format '{{.Names}}' 2>/dev/null | grep -qi buildbud; then echo 'RUNNING — this host already hosts a BuildBud instance'; else echo 'none detected'; fi)
- **Install dir:** $(d=$(ls -d /home/*/buildbud /home/*/.buildbud-server ./install 2>/dev/null | head -5 | tr '\n' ' '); [[ -n "$d" ]] && echo "$d" || echo 'none')

## Genesis readiness (heuristic)
$(
  score=0; notes=""
  have docker && score=$((score+1)) || notes+="- Install Docker + compose (required for the BuildBud stack).\n"
  { have ufw || have fail2ban-client; } && score=$((score+1)) || notes+="- No firewall/fail2ban — run \`harden.sh\` before exposing.\n"
  have tailscale && score=$((score+1)) || notes+="- No Tailscale — private access recommended for pre-alpha.\n"
  echo "**Readiness: ${score}/3 baseline signals present.**"
  [[ -n "$notes" ]] && { echo ""; echo "Recommended before \`genesis start\`:"; echo -e "$notes"; } || echo "Baseline looks good — proceed to \`genesis start\`."
)
REPORT
}

if $TO_STDOUT; then emit; else emit > "$OUT"; ok "Wrote $OUT"; fi
